development:
  adapter: postgresql
  database: prokeys_development
  pool: 5
  timeout: 5000
  username: "postgres"
  password: <%= Rails.application.secrets[:postgres] %>
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000